version: "3.8"
services:
  db:
    image: mysql:8.0
    container_name: minijuego_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: minijuego
    ports:
      - "3306:3306"
    volumes:
      - ./Database/init.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 1234
